//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PandaVideo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PandaVideo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pandasoft Video Converter.
        /// </summary>
        public static string AboutLabelTitle {
            get {
                return ResourceManager.GetString("AboutLabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools used:.
        /// </summary>
        public static string AboutToolsUsed {
            get {
                return ResourceManager.GetString("AboutToolsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        public static string BatchAdd {
            get {
                return ResourceManager.GetString("BatchAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string BatchClear {
            get {
                return ResourceManager.GetString("BatchClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add DVD....
        /// </summary>
        public static string BatchDVD {
            get {
                return ResourceManager.GetString("BatchDVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string BatchRemove {
            get {
                return ResourceManager.GetString("BatchRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string ButtonCheckForUpdates {
            get {
                return ResourceManager.GetString("ButtonCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string ButtonConvert {
            get {
                return ResourceManager.GetString("ButtonConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Ringtone.
        /// </summary>
        public static string CheckBoxAudioRingtone {
            get {
                return ResourceManager.GetString("CheckBoxAudioRingtone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically check for updates on startup.
        /// </summary>
        public static string CheckBoxAutoUpdates {
            get {
                return ResourceManager.GetString("CheckBoxAutoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode Subtitles.
        /// </summary>
        public static string CheckBoxEncodeSubtitles {
            get {
                return ResourceManager.GetString("CheckBoxEncodeSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Video Recode.
        /// </summary>
        public static string ForceVideoRecode {
            get {
                return ResourceManager.GetString("ForceVideoRecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Andy Tather (c) Copyright 2014.
        /// </summary>
        public static string LabelCopyright {
            get {
                return ResourceManager.GetString("LabelCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device:.
        /// </summary>
        public static string LabelDevice {
            get {
                return ResourceManager.GetString("LabelDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Folder:.
        /// </summary>
        public static string LabelOutputFolder {
            get {
                return ResourceManager.GetString("LabelOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Audio Language:.
        /// </summary>
        public static string LabelPrefAudioLang {
            get {
                return ResourceManager.GetString("LabelPrefAudioLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source File.
        /// </summary>
        public static string LabelSourceFile {
            get {
                return ResourceManager.GetString("LabelSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Folder:.
        /// </summary>
        public static string LabelWorkingFolder {
            get {
                return ResourceManager.GetString("LabelWorkingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TabHeaderAbout {
            get {
                return ResourceManager.GetString("TabHeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string TabHeaderBatch {
            get {
                return ResourceManager.GetString("TabHeaderBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string TabHeaderOutput {
            get {
                return ResourceManager.GetString("TabHeaderOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Details.
        /// </summary>
        public static string TabHeaderSourceDetails {
            get {
                return ResourceManager.GetString("TabHeaderSourceDetails", resourceCulture);
            }
        }
    }
}
